name: Audit Preview Deploys

on: [deployment, deployment_status]

jobs:
  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name : 'Log deployment'
        run: 'echo ${{ github.event.deployment.url }}'
