name: Audit Preview Deploys

on:
  deployment

jobs:
  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name : 'Log deployment'
        run: 'echo ${{ event.deployment.url }}'
